server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # 关键：在 Docker 网络里，直接用后端容器的名字，且目标是容器内的 5000 端口
        proxy_pass http://backend-test:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}